general {
    hide_cursor = false # 不隐藏光标
}

animations {
    enabled = true                              # 启用动画效果
    bezier = linear, 1, 1, 0, 0                 # 匀速变化
    animation = fadeIn, 1, 5, linear            # 进入锁屏的动画
    animation = fadeOut, 1, 5, linear           # 退出锁屏的动画
    animation = inputFieldDots, 1, 2, linear    # 密码点动画
}

# 锁屏背景
background {
    path = ~/.config/hypr/hyprlock_background.jpeg    # 锁屏背景路径
}

# 密码输入框
input-field {
    size = 250, 50                       # 尺寸, 宽:250 高:50
    rounding = 8                         # 圆角半径,值越大,输入框的四个角就越圆 (另外, -1 表示完全圆角)
    position = 0, -50                    # 坐标
    outline_thickness = 1                # 外边框厚度
    inner_color = rgba(255, 255, 255, 1) # 内盒颜色:    白色
    outer_color = rgba(52, 152, 219, 1)  # 外边框颜色:  蓝色
}

# 时间显示
label {
    text = cmd[update:1000] echo "$(date '+%H:%M')"    # 显示内容,这里调用命令 date 获取时间
    font_size = 108                                    # 文本大小
    position = 0, 320                                  # 文本位置
    color = rgba(120, 140, 170, 1)                     # 文本颜色: 轻粉蓝
}

label {
    text = cmd[update:1000] echo "$(date '+%F')"       # 显示内容,这里调用命令 date 获取时间
    font_size = 30                                     # 文本大小
    position = 0, 200                                  # 文本位置
    color = rgba(120, 140, 170, 1)                     # 文本颜色: 轻粉蓝
}
